### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by svetlemodry** [ugoviti/synbak#4]
Hi!
Would it be possible to tag the versioned releases, so that the releases and tags [pages](https://github.com/ugoviti/synbak/releases) would show the latest versions along with tarballs of the source? This would make [packaging](https://www.archlinux.org/packages/community/any/synbak/) the software easier for me. The initzero.it project [homepage](http://www.initzero.it/products/opensource/synbak) page seems to be gone.
Thanks!

**Comment by ugoviti** [comment]
Hi, sure! I had forgotten it :)
before github, synbak was versioned inside an internal svn repo, so previous releases doesn't exist.
I just tagged 3.6 and 3.7 version.

The old corporate repo is gone for now. Github is the official repo since synbak-3.6.

Anyway old tarballs are always located here:

http://www.initzero.it/products/opensource/synbak-VERSION.tar.gz

example:

http://www.initzero.it/products/opensource/synbak-3.6.tar.gz

Kind regards

**Comment by ugoviti** [comment]
Fixed with 3.7 release. thank you!

**Comment by svetlemodry** [comment]
Awesome, thanks for the quick action!
